theme: jekyll-theme-cayman
title: Remedi - A step in the right direction.
description: Parkinson's Project Website for CMPT 275 - Created by students at Simon Fraser University
baseurl: /cmpt275_fa2019_team8


